services:
  filebrowser:
    image: filebrowser/filebrowser:v2.63.23@sha256:a469ea076d4a1b4b1d86a41d130f2f536cd9da996a2b1fb39c0d7635f9d89b9a
    container_name: filebrowser
    user: 1000:1000
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - 'filebrowser_config:/config'
      - 'filebrowser_database:/database'
      - 'filebrowser_data:/srv'

volumes:
  filebrowser_config:
  filebrowser_database:
  filebrowser_data:
