services:
  filebrowser:
    image: filebrowser/filebrowser:v2.63.17@sha256:271ec822a03112ee8d2fc7042e8434995dfa74421e6a48e031be68c88fcded1c
    container_name: filebrowser
    user: 1000:1000
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - 'filebrowser_config:/config'
      - 'filebrowser_database:/database'
      - 'filebrowser_data:/srv'

volumes:
  filebrowser_config:
  filebrowser_database:
  filebrowser_data:
