services:
  filebrowser:
    image: filebrowser/filebrowser:v2.63.4@sha256:69131aef9a415cbb0d62ada500ffdfbfe1a535ab860b429fd360676c00f84d1b
    container_name: filebrowser
    user: 1000:1000
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - 'filebrowser_config:/config'
      - 'filebrowser_database:/database'
      - 'filebrowser_data:/srv'

volumes:
  filebrowser_config:
  filebrowser_database:
  filebrowser_data:
