services:
  filebrowser:
    image: filebrowser/filebrowser:v2.63.2@sha256:4dce87308b9f9cfbcf8d0a284fc9565d2b515530a6bae2d920b388161e093f26
    container_name: filebrowser
    user: 1000:1000
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - 'filebrowser_config:/config'
      - 'filebrowser_database:/database'
      - 'filebrowser_data:/srv'

volumes:
  filebrowser_config:
  filebrowser_database:
  filebrowser_data:
