services:
  filebrowser:
    image: filebrowser/filebrowser:v2.59.0@sha256:6e950e90bae0c53c27f4be6eeeb88e4b9cffc1f9be05ca2a0c09e74663ae595d
    container_name: filebrowser
    user: 1000:1000
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - 'filebrowser_config:/config'
      - 'filebrowser_database:/database'
      - 'filebrowser_data:/srv'

volumes:
  filebrowser_config:
  filebrowser_database:
  filebrowser_data:
