services:
  n8n:
    container_name: n8n
    restart: always
    image: docker.n8n.io/n8nio/n8n:stable@sha256:cae1f28d585a99d9ce9a56f82fbfc99fc100862ffef988d73fa2048d2687b0cc
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=https
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - WEBHOOK_URL=https://${WEBHOOK_URL}
      - N8N_PROXY_HOPS=1
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
    ports:
      - 8080:5678
    volumes:
      - n8n_data:/home/node/.n8n
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider http://localhost:5678/healthz || exit 1']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

volumes:
  n8n_data:
