services:
  caddy:
    container_name: caddy
    build: .
    restart: unless-stopped
    environment:
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      CF_API_TOKEN: ${CF_API_TOKEN}
      DOMAIN_NAME: ${DOMAIN_NAME}
      INTERNAL_CORS_ORIGIN_ESCAPED_DOMAIN: ${INTERNAL_CORS_ORIGIN_ESCAPED_DOMAIN}
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 10m
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  caddy_data:
  caddy_config: