services:
  caddy:
    env_file: .env
    image: custom-caddy:latest
    build: .
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 10m
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  caddy_data:
  caddy_config: