services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.8@sha256:1694ff069f0c9dafb283c36765175606866769f5d72f2ed56b6a0f1be922fc37
    container_name: jellyfin
    user: 1000:1000
    group_add:
      - "992"
    ports:
      - "8080:8096"
      - "8080:8096/udp"
      - "7359:7359/udp"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: /mnt/data/media
        target: /media
        read_only: true
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_URL}
      - TZ=${TIMEZONE}
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
