services:
    speedtest:
        container_name: openspeedtest
        image: openspeedtest/latest:v2.0.6@sha256:a6a7e3b3e9e93cfe7b9b2eb49c60b2a93644149a0a600845d4df57148b193ff6
        env_file: .env
        environment:
            - DOMAIN_NAME=${DOMAIN_NAME}
            - USER_EMAIL=${USER_EMAIL}
        restart: unless-stopped
        ports:
            - "80:3000"
            - "80:3000/udp"
            - "443:3001"
            - "443:3001/udp"
