services:
    speedtest:
    env_file: .env
    environment:
        - ENABLE_LETSENCRYPT=True
        - DOMAIN_NAME=${DOMAIN_NAME}
        - USER_EMAIL=${USER_EMAIL}
        - VERIFY_OWNERSHIP=${VERIFY_OWNERSHIP}
    restart: unless-stopped
    container_name: openspeedtest
    ports:
        - "80:3000"
        - "443:3001"
    image: openspeedtest/latest
