services:
  convertx:
    container_name: convertx
    env_file: .env
    image: ghcr.io/c4illin/convertx@sha256:2397d94fa091e48f1fbfcb97dd28d6c36cf7bdac2a33fb5cd66813e6ab723849
    restart: unless-stopped
    ports:
      - "8080:3000"
    environment:
      - ALLOW_UNAUTHENTICATED=true
      - AUTO_DELETE_EVERY_N_HOURS=6
      - JWT_SECRET=${JWT_SECRET}
      - FFMPEG_ARGS=-c:v libx265 -preset slow -c:a copy -map_metadata 0
    volumes:
      - ./data:/app/data