services:
  convertx:
    container_name: convertx
    image: ghcr.io/c4illin/convertx:v0.16.1@sha256:1402221b314c794e918a219b7f7698a214e447304472ca406acccc91e9537e63
    restart: unless-stopped
    ports:
      - "8080:3000"
    environment:
      - ALLOW_UNAUTHENTICATED=true
      - AUTO_DELETE_EVERY_N_HOURS=6
      - JWT_SECRET=${JWT_SECRET}
      - FFMPEG_ARGS=-c:v libx265 -preset slow -c:a copy -map_metadata 0
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
