services:
  convertx: 
    env_file: .env
    image: ghcr.io/c4illin/convertx@sha256:346589f154332997329fdc888417d4b24c49cc9140eab80e637a68cfbdd8041b
    container_name: convertx
    restart: unless-stopped
    ports:
      - "443:3000"
    environment:
      - ALLOW_UNAUTHENTICATED=true
      - AUTO_DELETE_EVERY_N_HOURS=6
      - JWT_SECRET=${JWT_SECRET}
      - FFMPEG_ARGS=-c:v libx265 -preset slow -c:a copy -map_metadata 0
    volumes:
      - ./data:/app/data