services:
  odoo:
    image: odoo:19.0@sha256:14c77d72303158553838d0f1e27f664b27bf79991eb9927fea98098cd011e20b
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8069"
    volumes:
      - odoo_data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - PGDATABASE=${POSTGRES_DB}
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
    command: --init base --db-filter=.* # Default username: admin, password: admin
    restart: unless-stopped
    networks:
      - odoo_net

  db:
    image: postgres:16@sha256:63e37736c98d5df8bd8fb122910d6d1812396c4311355754fffc150efd5fe4bf
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - odoo_net

volumes:
  odoo_data:
  db_data:

networks:
  odoo_net:
