services:
  # --- Network & VPN Gateway ---
  gluetun:
    image: ghcr.io/qdm12/gluetun:v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080 # qBittorrent WebUI
      - 6881:6881 # TCP Peering
      - 6881:6881/udp # UDP Peering
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_ENDPOINT_IP=${WIREGUARD_ENDPOINT_IP}
      - WIREGUARD_ENDPOINT_PORT=${WIREGUARD_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - WIREGUARD_MTU=1280
    volumes:
      - ./config/gluetun:/gluetun
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://www.google.com || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - arr-net

  # --- Download Client ---
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:20.04.1@sha256:fc98c8af048936d0070dc5e5992feab08664f8a61a860d91be02f782f8721485
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/qbittorrent:/config
      - ${HOST_DIR}:/data
    network_mode: "service:gluetun"
    restart: unless-stopped
    healthcheck:
      test: curl --head --fail http://localhost:8080/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  # --- Extraction Manager ---
  unpackerr:
    image: golift/unpackerr:0.14.5@sha256:8493ffc2dd17e0b8a034552bb52d44e003fa457ee407da97ccc69328bce4a815
    container_name: unpackerr
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
      ## Global Settings
      - UN_DEBUG=false
      - UN_QUIET=false
      - UN_ERROR_STDERR=false
      - UN_ACTIVITY=false
      - UN_LOG_QUEUES=1m
      - UN_LOG_FILE=/config/unpackerr.log
      - UN_LOG_FILES=10
      - UN_LOG_FILE_MB=10
      - UN_LOG_FILE_MODE=0600
      - UN_INTERVAL=2m
      - UN_START_DELAY=1m
      - UN_RETRY_DELAY=5m
      - UN_MAX_RETRIES=3
      - UN_PARALLEL=1
      - UN_FILE_MODE=0644
      - UN_DIR_MODE=0755
      - UN_SONARR_0_URL=${SONARR_URL}
      - UN_SONARR_0_API_KEY=${SONARR_API_KEY}
      - UN_RADARR_0_URL=${RADARR_URL}
      - UN_RADARR_0_API_KEY=${RADARR_API_KEY}
    volumes:
      - ./config/unpackerr:/config
      - ${HOST_DIR}:/data
    restart: unless-stopped
    networks:
      - arr-net

  # --- The "Managers" ---
  radarr:
    image: lscr.io/linuxserver/radarr:6.0.4@sha256:6d3e68474ea146f995af98d3fb2cb1a14e2e4457ddaf035aa5426889e2f9249c
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/radarr:/config
      - ${HOST_DIR}:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - arr-net

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.16@sha256:37be832b78548e3f55f69c45b50e3b14d18df1b6def2a4994258217e67efb1a1
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/sonarr:/config
      - ${HOST_DIR}:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - arr-net

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.3.0@sha256:e74a1e093dcc223d671d4b7061e2b4946f1989a4d3059654ff4e623b731c9134
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - arr-net

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.6@sha256:7962759d99d7e125e108e0f5e7f3cdbcd36161776d058d1d9b7153b92ef1af9e
    container_name: flaresolverr
    environment:
      - TZ=${TZ}
    ports:
      - 8191:8191
    restart: unless-stopped
    networks:
      - arr-net

  bazarr:
    image: lscr.io/linuxserver/bazarr:1.5.5@sha256:1cf40186b1bc35bec87f4e4892d5d8c06086da331010be03e3459a86869c5e74
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/bazarr:/config
      - ${HOST_DIR}:/data
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - arr-net

  recommendarr:
    image: tannermiddleton/recommendarr:v1.4.4@sha256:c946dd24542ab3cf6b0d56ab1d69e1ea1ff1d84f8a293ceeeaf3f53f09e50db6
    container_name: recommendarr
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=false 
      - PORT=3000
      - PUBLIC_URL=http://localhost:3000
    volumes:
      - ./config/recommendarr:/app/server/data
    restart: unless-stopped
    networks:
      - arr-net

  # --- Quality Profile Sync ---
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:8.2.1@sha256:791bdc0d2a35b0f24b89a0b14159591269ef070f19fcccfc5fb518a863141373
    container_name: recyclarr
    user: ${PUID}:${PGID}
    volumes:
      - ./config/recyclarr:/config
    environment:
      - TZ=${TZ}
      - SONARR_URL=${SONARR_URL}
      - SONARR_API_KEY=${SONARR_API_KEY}
      - RADARR_URL=${RADARR_URL}
      - RADARR_API_KEY=${RADARR_API_KEY}
    networks:
      - arr-net
    restart: unless-stopped

  huntarr:
    image: ghcr.io/plexguide/huntarr:9.3.7@sha256:95e88b2595f71b1ec2e158a3b9461c573e192928c51ac2b0d9675f33d4cdba15
    container_name: huntarr
    restart: always
    volumes:
      - ./config/huntarr:/config
    environment:
      - TZ=${TZ}
    ports:
      - 9705:9705
    networks:
      - arr-net

  # --- Requests ---
  seerr:
    image: ghcr.io/seerr-team/seerr:v3.0.1@sha256:1b5fc1ea825631d9d165364472663b817a4c58ef6aa1013f58d82c1570d7c866
    init: true
    container_name: seerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/seerr:/app/config
    ports:
      - 5055:5055
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
    networks:
      - arr-net

networks:
  arr-net:
    driver: bridge
    attachable: true
