services:
  # --- Network & VPN Gateway ---
  gluetun:
    image: ghcr.io/qdm12/gluetun:v3.41.0@sha256:6b54856716d0de56e5bb00a77029b0adea57284cf5a466f23aad5979257d3045
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080 # qBittorrent WebUI
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_ENDPOINT_IP=${WIREGUARD_ENDPOINT_IP}
      - WIREGUARD_ENDPOINT_PORT=${WIREGUARD_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
    volumes:
      - ./config/gluetun:/gluetun
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://www.google.com || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - arr-net

  # --- Download Client ---
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.4@sha256:b8a08ffba8850e2e71153e153cf5eed2dedbf499ef9b123262735ce924b65586
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/qbittorrent:/config
      - ${HOST_DIR}:/data
    network_mode: "service:gluetun"
    restart: unless-stopped
    healthcheck:
      test: curl --head --fail http://localhost:8080/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  # --- Extraction Manager ---
  unpackerr:
    image: golift/unpackerr@sha256:a9e7eb0d7b0ca16d2bdcb5af52eb4b544053ad6d915dd9b0f8383bc83f1df5cc
    container_name: unpackerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_SONARR_0_API_KEY=${SONARR_API_KEY}
      - UN_RADARR_0_URL=http://radarr:7878
      - UN_RADARR_0_API_KEY=${RADARR_API_KEY}
    volumes:
      - ./config/unpackerr:/config
      - ${HOST_DIR}:/data
    restart: unless-stopped
    networks:
      - arr-net

  # --- The "Managers" ---
  radarr:
    image: lscr.io/linuxserver/radarr:6.0.4@sha256:270f25698624b57b86ca119cc95399d7ff15be8297095b4e1223fd5b549b732c
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/radarr:/config
      - ${HOST_DIR}:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - arr-net

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.16@sha256:02b4d538d351d6e35882a021c08e8600fe95d28860fb1dd724b597166e7221ca
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/sonarr:/config
      - ${HOST_DIR}:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - arr-net

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.3.0@sha256:d3e9307b320b6772749a2cf8fc2712e9e824c4930b034680ad4d08a9e2f25884
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - arr-net

  bazarr:
    image: lscr.io/linuxserver/bazarr:1.5.4@sha256:d6492cc79ca5e12fe617c7285e7ebd60d4e7f0e93ec7faa78338dba91f07a91e
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/bazarr:/config
      - ${HOST_DIR}:/data
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - arr-net

  # --- Quality Profile Sync ---
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:2.1.2@sha256:84d3474d2bb6e8e99dac3748b6327301ac28c2d32bea4fa4b8e190c9c4b2ac77
    container_name: recyclarr
    user: ${PUID}:${PGID}
    volumes:
      - ./config/recyclarr:/config
    environment:
      - TZ=${TZ}
    networks:
      - arr-net
    restart: unless-stopped

  # --- Requests ---
  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:2.7.3@sha256:9cc9e9ee6cd5cf5a23feb45c37742ba34cfd6314d81d259cddb373a97ac92cdd
    container_name: jellyseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/jellyseerr:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped
    networks:
      - arr-net

networks:
  arr-net:
    driver: bridge
    attachable: true
