services:
  video-converter:
    container_name: video-converter
    image: ghcr.io/gatanasi/video-converter:2.3.1@sha256:d6d1cb47ba27b2920ada2e5b9ccd4311e5816d6d14accc650f3ea867414dd05c
    restart: unless-stopped
    ports:
      - "8080:3000"
    environment:
      GOOGLE_DRIVE_API_KEY: ${GOOGLE_DRIVE_API_KEY}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      WORKER_COUNT: ${WORKER_COUNT}
      DEFAULT_DRIVE_FOLDER_ID: "${DEFAULT_DRIVE_FOLDER_ID:-}"
    init: true
    volumes:
      - ./uploads:/app/uploads
      - ./converted:/app/converted
    cap_add:
      - SYS_NICE
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/config"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s