services:
  mediamanager:
    container_name: mediamanager
    image: ghcr.io/maxdorninger/mediamanager/mediamanager:1.12.2@sha256:6092302f2f6b3ba931eae5c5f9164d43bcfd61c28b46c11477270328e92f1aa8
    ports:
      - "8080:8000"
    env_file:
      - .env
    volumes:
      # Mount your actual media directories here - these paths should match your config.toml
      - /mnt/data/test/:/data/
      # Config folder for application configuration
      - ./config/:/app/config/
      # Image folder
      - ./images/:/data/images/
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: mediamanager_postgres
    image: postgres:17.7@sha256:2006493727bd5277eece187319af1ef82b4cf82cf4fc1ed00da0775b646ac2a4
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
